services:
  - type: web
    name: baard
    runtime: static
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: "20"
